=head1 NAME

POE::Component::IRC::Cookbook::Reload - Reload your bot's code after a change

=head1 SYNOPSIS

Wouldn't it be neat if you could update your bot's code, and have the changes 
be applied without dropping the connection to the IRC server?

=head1 DESCRIPTION

At first, this might seem complicated. You might have to mess with
C<eval STRING>/C<do FILE>, deal with scoping issues and what not. But when
you really think about it, all you need is an IRC proxy. Let the proxy
handle the IRC connection, and let the bot run as a separate process which
you can restart at will.

L<POE::Component::IRC|POE::Component::IRC> itself can act as a proxy. See
the L<Proxy|POE::Component::IRC::Plugin::Proxy> plugin for details.

=head1 AUTHOR

Hinrik E<Ouml>rn SigurE<eth>sson, hinrik.sig@gmail.com

